### ISSUE TITLE
숙소 등록에 관한 이슈

### ISSUE THREAD

**Issue by SeokBin02** [ClonePjtAirBB/BE_ClonePjtAirBB#15]
숙소등록을 UI없이 포스트맨에 의존해서 데이터 입력을 목적으로 설계한 API였고 그러다 보니 데이터 입력을 한번에 받는 설계를 하고 있었습니다.  여기서 모든 정보를 단일 dto로 받기 때문에 필드의 양이 많아졌고, 그에 따른 생성자가 비대해졌으며, 이 data를 stay 객체로 인스턴스화 하는 과정에서 너무 많은 필드를 stay가 가지고 있으면 stay를 조회할 때마다 해당 필드들을 다 가져와야하는 리소스 낭비를 고려해서 ERD를 작성했고, 실제로 설계할때 크게 연관없이 연관관계 설정을 해놓은게 마음에 안들었습니다.

![hostRequsetDTO](https://lh3.googleusercontent.com/fife/APg5EObLwg_e4EJI_qwbjTRIOb9AZSXYkLyqKokKqH5CHbq-8PoMZz-xjJCQbPK9C77akXaJtjER-_WzrScT0_gh_dp-aEqEc2pq-nC6h5Trwkusjvupejl0SZff5ON4Ina5SG6XeGZTdTvVHsh_SdIKzWyDAdSulwKpa9Ir53u1cxQ8SLRL9SgesLNfoMWNRWQnAVgLLIiqFRF3vXd2EnWWrCY5N4Xwtp1HLbSWKwp43TnqDAfOkfnZARNbJCRD-MFHlXxGMwPQbZ-jOaAsoXBnoa4aK0VMHTv_6qATCkQ3VZOMgSO-N27iH7qyHRy2UAsYznde52lcFON8ilE3Z-tlVNL5FoQR06cEAyDNCrGx51eZpBIVSVrkqoC1r2kHuSXOFmxw5T-QnMdIsDCPHGwkIfsDNfOSxeUoa2o2doRqyRyLUa-10U34uAzRBpRqzHUrvKFoicXb_ZBoPujS0rY86_cCW9FZGv8wbkuLcyLt3C4j0C16J8MEpXqaQLBE5TSP_5KVBrfoKwNNlHjsTdNk0H1UQACBllxEav86FhuUnWCrhJ1JTSFqGWfNgLjPjYuXS_MFCuNssRLNmX40iaoAlzIIGcNUVIfw_0f7W81k_-0GStUjU2F3xih1mj4g7-WXC1_RFtK1I1yWSi_45677rsOUm2c59uXL6W3dSn4hFN1i2i6jrBDXamI1amsp-h49UDmq-v-NnnBIzkCG35nUx9kl-wp-RG_apJyAUIhOcUad4sdOPw1oWDOz82-H26hUWfT3QpusKhjr8bTfokASTg8XxdEdXmBwRHW9Q7cTguCFhIaK8HPFS9iwKQF3yw01J8DYoN1Ohx7sOT3FPd590k7m5RqkSMtQ3Co7psgmBQzPNVw6fRozVQMsfD4NXCuRn4yU3xeUP4QYUUxmGedmwS1fazpVdrzpZFszXiGAim0olk-HtJ6CIXLbrddwVoULNXLq3qOYmfjxOGXmGW5S92CuoRpHqu5N_NWs4SmzlKKrKLq8YODnEvNyzo5uOgwm9uB-8X7q76SBXeg8NDn6oyRDnn3DA_2LmrX3y5drxsWhP6PVQ3or-0NOM6xZnJ8w2wMvtMJjb8xW0a7jdjukQkwNyyEAL7Pij6lJC-3wQz5mQ4dLImjRDwV6qdTKuNiz2jZYo8RQ4DCuPZ5iiZrbgX-B_FTCPkkxX0anoE7-WvMJr2inPy59zPHjHvC7JPZYBdKAGPEdppD6xgt_uLYFCn_h-RZ9vap6-LjP-1oKYBjnqez0QyBfjHtK5nTQGR0D44OE1Twz6Buy4QOgaC3ftvU5OS5sv57s1l3EIMQWGcwbdtPf13d6mskew3VtdNMPJ2Xq2aBsV_XiIRzUAycISNjggeHZMDSwfJHyUE-bfeyKfW73r3CjKW-KkOvTWW2LYAISf9gdBjCQ2Uf2EwTze5xyNjc6XI8tbc3yaUQCToZT-EWtAk3AW2nT1-Tt4kFzTciCmgXwvaYwg3NzSfzyC51RUA=w1920-h937)
이부분에 대해서 AIRBNB의 숙소 등록을 실제로 하면서 URL을 분석해본결과..
http://host:port/URL(ex: api/stay) 로 되어 있는 것과 달리
https://www.airbnb.co.kr/become-a-host/890463390203195454/privacy-type
https://www.airbnb.co.kr/become-a-host/890463390203195454/location

이와 같은 서브 api 구조로 되어 있는데 이것을 nested resources 개념이라고 합니다.
지금은 프론트가 없이 데이터를 서버에 넣기 위한 목적으로 만든 api라 비효율적으로 설계를 했지만 nested resources 디자인 패턴을 사용하면 복잡한 데이터 모델을 효율적으로 다룰 수 있으며, URI 경로를 통해 자원 간의 관계를 명확하게 표현할 수 있다고 합니다.

https://restfulapi.net/resource-naming/ 매니저님이 피드백 해준 자료를 참고하시면 될 것 같습니다.

**Comment by mottoslo** [comment]
890463390203195454과 같은 숫자가 becom-a-host의 인스턴스 URI고, location과 같은 하위 URI에 값을 쌓아서 최종 완료할 때 숙소정보를 생성하는 것 같습니다..! 유저가 숙소정보를 등록하다가 중간에 나가도, 어떻게 다음에 이어서 작성할 수 있는지 궁금했는데 저런 방식이면 임시 인스턴스를 불러오는 방식으로 이해가 되네요...! 메소드들도 단일책임으로 숙소정보를 받을 수 있어서 좋을 것 같습니다. 지금은 RegisterStayRequest가 너무너무 많은 일을 하고 있습니다

**Comment by mottoslo** [comment]
시간부족으로 X
