### ISSUE TITLE
사용자 인증 로직 수정 및 추가 기능 구현 필요

### ISSUE THREAD

**Issue by Omakmusae** [ClonePjtAirBB/BE_ClonePjtAirBB#25]
- 사용자 인증 필요 없는 로직이면 anonymous 로그인 로직으로 수정 필요
- aws 과금 이슈로 인한 페이징 처리 기능 구현 필요

**Comment by mottoslo** [comment]
일단 토큰 없으면 회원가입 된 유저중에 tempuser 세팅하도록 하였고,
페이징은 구현하기 전까지 일단 전체조회에서 20개만 가져오도록 해놨습니다.

나중에 조치하면 issue 닫겠습니다

**Comment by mottoslo** [comment]
추가로,  post맨에서 요청 Authentication을 쿠키로 전달하는 법도 알아야합니다 (jwt토큰 전달방식을 cookie로 바꿨는데, 쿠키는 브라우저에서 처리해주는 거라서 저희가 요청 받을 때도 cookie로 받아야 한다고 합니다)

**Comment by mottoslo** [comment]
구현완

요청 authentication은 브라우저에서 자동으로 세팅해주고, 서버에서는 request.getCookie를 통해 가져올 수 있습니다.
다만, 쿠키를 세팅해줄 때 path를 같이 세팅해주어야 해당 path들에 맞는 요청에 쿠키가 포함되어 요청이 가게됩니다.
