### ISSUE TITLE
[FE] 전체 조회에서 들어오는 데이터와 API 명세서 response 데이터 차이

### ISSUE THREAD

**Issue by xxyeon129** [ClonePjtAirBB/BE_ClonePjtAirBB#37]
전체 조회에서 응답받는 response 데이터가 API 명세와 다릅니다. 
`id`, `img`가 누락되었는데 반영하시는 중인건가요?

- API 명세
```
[
  {
 “stayId” : 3
 “country” : “대한민국”,
 “city”: “서울”
 “host”: “Oliver”,
 ”costperday”: 166698
 ”filter”: “공동 주택”,
”img”: “imgurl”
  },
  {...}
]
```
- 들어오는 데이터
<img width="205" alt="스크린샷 2023-05-17 오전 6 44 32" src="https://github.com/ClonePjtAirBB/BE_ClonePjtAirBB/assets/102347529/2989209e-638b-46a4-ad7c-b9f0e3ef85ea">

**Comment by mottoslo** [comment]
id는 추가해놓았고, imgurl은 thumbnailUrl로 가고있던 걸 수정했는데, 배포를 안해서 이전 버전이었나 봅니다 ....죄송하빈다
