### ISSUE TITLE
[FE] 필터 조회 400 에러

### ISSUE THREAD

**Issue by xxyeon129** [ClonePjtAirBB/BE_ClonePjtAirBB#39]
`http://43.200.169.48/api/stay/search?country=KOREA` url으로 포스트맨에 GET 요청 시 아래와 같은 400 에러가 뜹니다. 아직 구현 중이라 그런건가요?

```
{
    "msg": "Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; For input string: \"search\""
}
```

<img width="1014" alt="스크린샷 2023-05-17 오전 6 47 49" src="https://github.com/ClonePjtAirBB/BE_ClonePjtAirBB/assets/102347529/dc67fbe4-523a-48fc-ab04-83d4d67243b3">

**Comment by Omakmusae** [comment]
필터 조회는 Params가 아닌 Body로 구현이 되어 있습니다.
Params에 country 체크를 해제하시고 Body 에 첨부 사진처럼 해주시면 조회 가능합니다
![image](https://github.com/ClonePjtAirBB/BE_ClonePjtAirBB/assets/106947027/cfcdc28a-f6d1-4f92-a1dc-3cbf837ac5af)

**Comment by xxyeon129** [comment]
프론트에서 GET 요청 보낼 시에는 body를 담아 보내는게 불가능합니다.
body가 들어가야 하는 거라면 POST 메소드로 바꾸셔야 할 것 같습니다.

**Comment by mottoslo** [comment]
승연님이 하신게 맞습니다 ! 에러난건 제가 어제 작업한거 배포를 안해서 이전 버전이라서 그랬던 거네요 ㅠㅠ... 너무 왔다갔다하면서 하다가 잊었습니다 죄송해요 .....
근홍님이 보신 postman도 get방식 pamram로 테스트한걸 postman에 저장 안해서 그렇게 나온 것 같습니다
