### ISSUE TITLE
[FE] API 명세 관련 논의가 필요한 사항

### ISSUE THREAD

**Issue by xxyeon129** [ClonePjtAirBB/BE_ClonePjtAirBB#40]
1. API 명세 필터 조회에서 쿼리 스트링에 checkout만 있는데 checkIn은 누락된건가요?
<img width="423" alt="스크린샷 2023-05-17 오전 6 50 45" src="https://github.com/ClonePjtAirBB/BE_ClonePjtAirBB/assets/102347529/36bfb810-f180-4129-a02c-fae7a2b7321c">
<img width="499" alt="스크린샷 2023-05-17 오전 6 51 49" src="https://github.com/ClonePjtAirBB/BE_ClonePjtAirBB/assets/102347529/6e34e126-ff00-482a-8a75-64426565cb86">   
   
2. 필터 조회에서 인원 추가 시 에어비앤비 홈페이지에서는 반려동물도 카운트되게 해서 UI 구현 시 동일하게 반려동물도 카운트할 수 있게 구현했는데, 반려동물 추가 시 `groupsize`에 카운트되는 걸로 할까요? 사람이 아니니까 따로 뺄지, 아니면 그냥 인원으로 칠지 논의해봐야 할 것 같습니다.   
   
<img width="444" alt="스크린샷 2023-05-17 오전 7 00 36" src="https://github.com/ClonePjtAirBB/BE_ClonePjtAirBB/assets/102347529/015b7fe4-b385-424c-b35a-d08371e279be">  

3. 필터 조회에서 나라 선택 시 한국과 일본 모두를 포함한 전체는 쿼리스트링값을 어떻게 드리면 되나요?  
ex) `?country=전체` `?country=ALL`  

4. API 명세에 'yyyy-mm-dd' 형식으로 적어놨었는데, 형식에 맞춰서 보내드릴 수 있지만 형식에 맞추다보니 코드량이 길어져서 'yyyy.mm.dd' 형식으로 쿼리스트링에 전달해도 될까요? 이미 구현한 내용이 있어 어렵다면, `yyyy-mm-dd` 형식 그대로 진행하겠습니다.  
ex) `?checkout_date=2023.05.24`

**Comment by mottoslo** [comment]
1. 예시로 적어놓은 건데, checkin이 누락된 게 맞는 것 같습니다.
2. 인원선택 부분은 성인 유아 이런식으로 세분화하지 않고, 그냥 인원수로 통일해서 저 부분은 구현이 어려울 것 같습니다. 반려동물 선택을 없애거나, groupSize에 포함시키는 방향으로 가야할것같아요
3. 전체는 그냥 ?country&city=asdklfj    식으로 country조건 안보내주시면 됩니다
4. 쿼리스트링에 .이 들어갈 수 있나요 ? 확인해보시고 답변 부탁드립니다 !
